[2025-02-04T09:35:14.659+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-04T09:35:14.673+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_workflow.full_transform manual__2025-02-04T09:35:04.073283+00:00 [queued]>
[2025-02-04T09:35:14.678+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_workflow.full_transform manual__2025-02-04T09:35:04.073283+00:00 [queued]>
[2025-02-04T09:35:14.678+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-02-04T09:35:14.685+0000] {taskinstance.py:2889} INFO - Executing <Task(_PythonDecoratedOperator): full_transform> on 2025-02-04 09:35:04.073283+00:00
[2025-02-04T09:35:14.692+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=155) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-04T09:35:14.693+0000] {standard_task_runner.py:72} INFO - Started process 158 to run task
[2025-02-04T09:35:14.694+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_workflow', 'full_transform', 'manual__2025-02-04T09:35:04.073283+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/test_dag.py', '--cfg-path', '/tmp/tmp6o5vbnkm']
[2025-02-04T09:35:14.695+0000] {standard_task_runner.py:105} INFO - Job 23: Subtask full_transform
[2025-02-04T09:35:14.738+0000] {task_command.py:467} INFO - Running <TaskInstance: test_workflow.full_transform manual__2025-02-04T09:35:04.073283+00:00 [running]> on host bcbdac0c6b51
[2025-02-04T09:35:14.817+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_workflow' AIRFLOW_CTX_TASK_ID='full_transform' AIRFLOW_CTX_EXECUTION_DATE='2025-02-04T09:35:04.073283+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-04T09:35:04.073283+00:00'
[2025-02-04T09:35:14.818+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-04T09:35:14.818+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-04T09:35:14.819+0000] {logging_mixin.py:190} INFO - Current task name:full_transform state:running start_date:2025-02-04 09:35:14.673953+00:00
[2025-02-04T09:35:14.819+0000] {logging_mixin.py:190} INFO - Dag name:test_workflow and current dag run status:running
[2025-02-04T09:35:14.819+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-04T09:35:14.836+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/lib/transform/transform_listings.py", line 29, in full_transform
    df = initialize_df(data)
         ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/lib/transform/transform_listings.py", line 7, in initialize_df
    df = pl.DataFrame(
         ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/polars/dataframe/frame.py", line 377, in __init__
    self._df = sequence_to_pydf(
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/polars/_utils/construction/dataframe.py", line 461, in sequence_to_pydf
    return _sequence_to_pydf_dispatcher(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/polars/_utils/construction/dataframe.py", line 590, in _sequence_of_sequence_to_pydf
    pydf = PyDataFrame.from_rows(
           ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 'data': unexpected value while building Series of type String; found value of type Int64: 4345291

Hint: Try setting `strict=False` to allow passing data with mixed types.
[2025-02-04T09:35:14.847+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-04T09:35:14.847+0000] {logging_mixin.py:190} INFO - Task start:2025-02-04 09:35:14.673953+00:00 end:2025-02-04 09:35:14.846919+00:00 duration:0.172966
[2025-02-04T09:35:14.848+0000] {logging_mixin.py:190} INFO - Task:<Task(_PythonDecoratedOperator): full_transform> dag:<DAG: test_workflow> dagrun:<DagRun test_workflow @ 2025-02-04 09:35:04.073283+00:00: manual__2025-02-04T09:35:04.073283+00:00, state:running, queued_at: 2025-02-04 09:35:04.099621+00:00. externally triggered: True>
[2025-02-04T09:35:14.848+0000] {logging_mixin.py:190} INFO - Failure caused by argument 'data': unexpected value while building Series of type String; found value of type Int64: 4345291

Hint: Try setting `strict=False` to allow passing data with mixed types.
[2025-02-04T09:35:14.848+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=test_workflow, task_id=full_transform, run_id=manual__2025-02-04T09:35:04.073283+00:00, execution_date=20250204T093504, start_date=20250204T093514, end_date=20250204T093514
[2025-02-04T09:35:14.859+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-04T09:35:14.860+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 23 for task full_transform (argument 'data': unexpected value while building Series of type String; found value of type Int64: 4345291

Hint: Try setting `strict=False` to allow passing data with mixed types.; 158)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 266, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/lib/transform/transform_listings.py", line 29, in full_transform
    df = initialize_df(data)
         ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/lib/transform/transform_listings.py", line 7, in initialize_df
    df = pl.DataFrame(
         ^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/polars/dataframe/frame.py", line 377, in __init__
    self._df = sequence_to_pydf(
               ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/polars/_utils/construction/dataframe.py", line 461, in sequence_to_pydf
    return _sequence_to_pydf_dispatcher(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/polars/_utils/construction/dataframe.py", line 590, in _sequence_of_sequence_to_pydf
    pydf = PyDataFrame.from_rows(
           ^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument 'data': unexpected value while building Series of type String; found value of type Int64: 4345291

Hint: Try setting `strict=False` to allow passing data with mixed types.
[2025-02-04T09:35:14.906+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-04T09:35:14.924+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-04T09:35:14.926+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
